### ISSUE TITLE
Add command line option to get version

### ISSUE THREAD

**Issue by packetfodder** [FairwindsOps/pentagon#101]
pentagon -v && pentagon --version do not return the current pentagon version, suggest we add a command line option to return the current version of pentagon.

$ pentagon -v
Error: no such option: -v
$ pentagon --version
Error: no such option: --version
$ pentagon --help
Usage: pentagon [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  add
  get
  start-project

**Comment by ejether** [comment]
closed by 6276ede0e14f4d5f4a98c026d6d20496da129cad
