### ISSUE TITLE
Better handling of aws secrets when adding a new inventory

### ISSUE THREAD

**Issue by sudermanjr** [FairwindsOps/pentagon#123]
Currently, the syntax for adding a new inventory requires this:

```
pentagon add inventory -Dtype=aws -Dname=prod -Daws_access_key=REDACTED -Daws_secret_key=REDACTED -D=aws_default_region=us-east-1
```

This is confusing since the start project syntax is:

```
pentagon add inventory -Dtype=aws -Dname=prod -Daws-access-key=REDACTED -Daws-secret-key=REDACTED -D=aws-default-region=us-east-1
```

It would be preferred to use the same syntax (dashes) for both.

**Comment by ejether** [comment]
Those look exactly the same to me. Is there a difference I'm not spotting?

**Comment by sudermanjr** [comment]
Underscores vs Dashes in the parameter names.

**Comment by ejether** [comment]
Ah, yes. 🤦‍♀️
