### ISSUE TITLE
System requirements are out of date

### ISSUE THREAD

**Issue by geojaz** [FairwindsOps/pentagon#129]
What should we do about this section? Does it make sense to list these versions out explicitly?

https://github.com/reactiveops/pentagon/blob/master/pentagon/component/core/files/README.md#system-requirements

**Comment by ejether** [comment]
At a minimum we should update the docs to match the current version.
Are you suggesting removing the version number entirely?

**Comment by geojaz** [comment]
I think short term, updating version number is better than leaving as is. But I feel like having a stack version in here is another thing to maintain that's not particularly valuable (IMO). 

Could we just say use the latest release of kops?

**Comment by ejether** [comment]
For kops specifically, that seems fine. Though it will be worth noting in the docs that choice of Kops version depends on the kubernetes version. If someone is running an older version of Kube, then they need an older version of Kops.

For Ansible and Terraform though, our modules aren't necessarily tested against the lastest versions so odd behaviors _may_ arise if they don't stick to our pinned versions.
