### ISSUE TITLE
Remove Makefile and yaml_source

### ISSUE THREAD

**Issue by coreypobrien** [FairwindsOps/pentagon#132]
Work on removing the makefile and yaml_source.

The goal is to not use make for scripty things.

**Comment by ejether** [comment]
The makefile has been removed but /bin/yaml_source is still being installed by pentagon. This is now provided by other internal tooling and should still be removed.

**Comment by ejether** [comment]
Makefile is already gone but `yaml_source` maybe should still be removed?
