### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by geojaz** [FairwindsOps/pentagon#133]
We have many changes in master since 2.3.1

**Comment by ejether** [comment]
While I'm not arguing against a release, we only have a small handful of changed in `master` currently.
https://github.com/reactiveops/pentagon/blob/master/CHANGELOG.md

I'd like to cut a release in the next couple weeks once:
https://github.com/reactiveops/pentagon/pull/131
https://github.com/reactiveops/pentagon/pull/120

Land.
#120 is going to take some more discussion before that is ready to see more work.
