### ISSUE TITLE
Pentagon start-project requires ~/workspace/projects/<project-name>

### ISSUE THREAD

**Issue by ejether** [FairwindsOps/pentagon#14]
`pentagon start-project` requires ~/workspace/projects/<project-name> to exist before it will create the infrastructure repository. The workspace directory should either be created or not required

**Comment by philipcristiano** [comment]
The reliance on a an RO convention seems out of place for Pentagon. Anecdotally I believe that most scaffolds need only the parent directory to exist, then they create the target directory themselves. 

The workspace is assumed as `~/workspace` (and configurable) but seems the part to specify should just be where to place the target directory, not specifying the start of an arbitrary tree.

**Comment by ejether** [comment]
I agree with your assessment.

**Comment by philipcristiano** [comment]
#50 at the moment still requires `~/workspace` but tells you the folder needed if it doesn't exist. Could be changed as well to default to the cwd

**Comment by ejether** [comment]
I believe this has been addressed recently and possible as part of #66
