### ISSUE TITLE
Migration branch name is not unique

### ISSUE THREAD

**Issue by sudermanjr** [FairwindsOps/pentagon#146]
If previous migrations have been run, there is already a migration branch.  This causes an error.

Maybe we should change the name of the branch to be unique to the current version or migration that is being run.

**Comment by ejether** [comment]
That was intentional. I made the assumption was made that the user would clean up the leftover `migration` branch and that there wouldn't end up being multiple migrations in flight at a time. 
Was that a bad assumption? Either way, better messaging around it would probably be useful.

**Comment by sudermanjr** [comment]
That's fine either way.  Better messaging might be good.  I just had the migration branch locally and it threw an error.  Took me a minute or two to realize.

**Comment by ejether** [comment]
resolved by #158
