### ISSUE TITLE
Fix getting started documentation

### ISSUE THREAD

**Issue by sudermanjr** [FairwindsOps/pentagon#163]
The getting started docs still mention the Makefile and are not coherent without it.

**Comment by ejether** [comment]
Some of this work has been covered by a community PR but a docs review is still in order.

**Comment by ejether** [comment]
It is important that the outcome of this is targetted at the community use of `pentagon` How we use the tool in our internal workflows will be documented internally.

**Comment by ejether** [comment]
I think the steps here will be to create a complete default infrastructure and document it, step by step, without using the internal tooling at all.

For bonus credit, do it with GCP/GKE, and for no standard infrastructures... like adding a new VPC or cluster.
