### ISSUE TITLE
Infrastructure repository Python requirements should be listed in the repository

### ISSUE THREAD

**Issue by philipcristiano** [FairwindsOps/pentagon#27]
After the repository is created it should contain a way to install the Python requirements needed to operate the infrastructure. 

An install of Pentagon includes the required dependencies but other users of the repo do not have a way to discover the versions of things they need installed. 

A `requirements.txt` file should be included that lists Pentagon or the required dependencies so that operators will be able to install them easily. Documentation about this should be added to the `README.md` that is generated for the project.

**Comment by ejether** [comment]
The idea has been for any pentagon requirements to be installed buy pip via `setup.py`  instead of `requirements.txt` and an extra step. If there are modules that are not currenlty installed that way, but are required, they should be added. 

Do you have any reasons why the `requirements.txt` is preferable to installation with `setup.py`?

**Comment by philipcristiano** [comment]
This is particular to the resulting repository. There is not a setup.py file there, the `requirements.txt` should be included as `lib/requirements.txt` so that it is included in the templated repository. 

If we want to have all users of the repository install Pentagon we should make it clear in the resulting repository how to do so (specifically which version). At the moment there are no tags or releases for the repo or PyPi Pentagon release. Otherwise the user may not have the correct versions of dependencies or know at all that they need to install Pentagon in order to get them.

**Comment by ejether** [comment]
I think I follow what you're saying. That an existing repository that has been cloned to a new users work station still needs a way to install modules required to use the infrastructure repository, correct?

What do you think belongs in the `requirements.txt`  at this point?

**Comment by philipcristiano** [comment]
For clients I've included `shyaml` and `ansible` (version locked) as requirements. `shyaml` is needed and not immediately obvious. `ansible`  mostly to keep the version the same as what I've used for development. 

I've also included `awscli` because that is generally helpful when working with AWS.

**Comment by ejether** [comment]
Ok, sounds good.

**Comment by philipcristiano** [comment]
`awscli` is actually required as part of the docs for VPN setup.
