### ISSUE TITLE
incorrect or superfluous variables in terraform.tfvars.jinja

### ISSUE THREAD

**Issue by opennomad** [FairwindsOps/pentagon#3]
in `lib/pentagon/components/vpc/files/terraform.tfvars.jinja` we have the 4 subnet_cidrs there (`/24`s)

Along with each of them there is a `*_subnet_parent_cidr`
it seems like all for of those parent CIDRs is `.0.0/22`.
if I take the default vpc_cidr of `10.10` and run it through ipcalc, only the `admin_subnet_cidrs` is actually part of if it's parent CIDR.

Best guess is that those parent declarations aren't used any longer.

**Comment by ejether** [comment]
@opennomad do you have any context on what those settings where use for initially? I'd like to be confident we aren't going to break anything before removing these.

**Comment by opennomad** [comment]
@ejether i do not not, but when I brought it up in the engineering channel it sounded like @sairez might have some recollection of those.

**Comment by sairez** [comment]
the `*_subnet_parent_cidr`was intended to umbrella the `*_subnet_cidr`s of the same type spanning AZs. This would allow all subnets of the same type to be referred to with one over-arching CIDR for purposes of ACLs or routing rules.

e.g. 

```
variable "admin_subnet_parent_cidr" {
    description = "parent CIDR for the administrative subnets"
    default = ".0.0/19"
}

variable "admin_subnet_cidrs" {
    description = "CIDRs for the adminsitrative subnets"
    default = {
      zone0 = ".0.0/21"
      zone1 = ".8.0/21"
      zone2 = ".16.0/21"
      zone3 = ".24.0/21"
    }
}
```

The x.x.0.0/19 admin parent cidr would contain ips from x.x.0.1-x.x.31.254, thus containing all the admin subnets spread across multiple zones.

While the variable itself may not be in use, I think that the concept is still important/relevant for organization across AZs.

**Comment by ejether** [comment]
Are the current values appropriate? If not, will on of you please determine the correct values and issue a PR?
