### ISSUE TITLE
Fill in `create-infrastructure-bucket` task

### ISSUE THREAD

**Issue by philipcristiano** [FairwindsOps/pentagon#30]
At the moment the `tasks/create-infrastructure-bucket.yml` file is a stub. It should have the automation to quickly and reliably create the bucket across infrastructure projects. 

https://github.com/reactiveops/pentagon/blob/08ac74bff910cdedf681fdfe63aa67d7461fe9be/lib/pentagon/tasks/create-infrastructure-bucket.yml

**Comment by emalloy** [comment]
work being done in `em/issue_32` https://github.com/reactiveops/pentagon/commit/89e50928c5d3bab83a57a528b932fdaf70fa422e#diff-3d84e1cf473528928cb8f58aa53eb17dR5

**Comment by philipcristiano** [comment]
Removed as part of #56
