### ISSUE TITLE
install-dependencies.sh should install specific versions

### ISSUE THREAD

**Issue by philipcristiano** [FairwindsOps/pentagon#31]
We should install version-locked dependencies as part of the `tasks/install-dependencies.sh` script. Updated brew recipes could install newer versions of software that is untested and potentially incompatible with Pentagon. Currently this also only supports brew-capable OSs (MacOS).

**Comment by ejether** [comment]
I think we should just remove this and document requirements

**Comment by philipcristiano** [comment]
Closed this in favor of the documentation in the README.
