### ISSUE TITLE
ansible-requirements should lock versions

### ISSUE THREAD

**Issue by philipcristiano** [FairwindsOps/pentagon#42]
[`ansible-requirements`](https://github.com/reactiveops/pentagon/blob/b7d60c0afcfa141bbb9a1dfc38312e34a687bb9a/lib/pentagon/ansible-requirements.yml) relies on multiple requirements using a `origin/master` ref. These refs are difficult to rely on over time as changes are made to the repositories. Pentagon's could have code that doesn't work with the `master` branch and users who install later could get a different version. 

These versions should be locked to specific versions to prevent incompatibles. 

Semi-related, there also appear to be requirements that are not used or documented in Pentagon such as `ansible-iam-role`

**Comment by ejether** [comment]
closed by 4e065e58a962bd201c902a4bae852a8085be607e
