### ISSUE TITLE
VPN provisioning fails on first run

### ISSUE THREAD

**Issue by philipcristiano** [FairwindsOps/pentagon#43]
When provisioning the VPN instance with Ansible I ran into the Pentagon selected image unable to install OpenVPN. It appears that the version to install was no longer available from the `security` repository provided by Ubuntu. Running `apt-get update` fixed it. I believe this was due to a stale cache of the apt repositories. 

Rerunning Ansible does not fix the issue. 

Including `apt-get update` as either `update_cache` or `cache_valid_time` for the VPN module should fix this.

**Comment by ejether** [comment]
I have run into this before on another AMI.

**Comment by ejether** [comment]
Can you share the error message? This issue probably ends up in an update for the https://github.com/reactiveops/Stouts.openvpn repository

**Comment by philipcristiano** [comment]
I don't have my history that long, even by time I fixed it it scrolled over. 

The fix/root issue would likely be in that repo, but for users of Pentagon also nice to have this as the first place to look.

**Comment by philipcristiano** [comment]
Added a PR tested with a client. It updates the cache if >1hour old which is enough to work with a newly instantiated AMI.

**Comment by philipcristiano** [comment]
Fixed in the linked PR. `origin/master` is used as the ref so new installs will get the change.
