### ISSUE TITLE
Add VPN instances to SSH Config

### ISSUE THREAD

**Issue by philipcristiano** [FairwindsOps/pentagon#46]
The `ssh_config` file should have the VPN instances added after the VPN is created. This may just be a documentation change. 

Adding the VPN to the SSH config will allow a consistent run of `ansible-playbook` without needing separate arguments depending on which playbook is run. 

Ref #44

**Comment by philipcristiano** [comment]
Would be interesting to see if we can automate adding the IP with http://docs.ansible.com/ansible/latest/lineinfile_module.html as part of the ansible run.

**Comment by ejether** [comment]
I looked into this but the vpn instance creation is in the same role as the vpn instance configuration.
I added a block in the `ssh_config` with '`*`' as the host and that works for the first run of the vpn role. We could setup a step _after_ the vpn instance is configured to replae that '`*`' with the actual ip address. 

I'm not sure how that would play when replaceing the vpn instance though.

**Comment by ejether** [comment]
fixed in #66
