### ISSUE TITLE
Support for multi-account AWS layouts

### ISSUE THREAD

**Issue by philipcristiano** [FairwindsOps/pentagon#48]
Account specific files are placed into a `default` folder without leaving a clear guideline about how to add more accounts or how to work with multiple accounts. Variables in `default/account/vars.yml` are not loaded into the shell but `default/account/vars.sh` are needed for working with kops. The kubectl (when generated) is placed into `config/private/` leading to a mismatch of where variables are needed to use kops. 

Proposal:

Start with making the layout easier with adding a second account. Move the `default` account into an `accounts` directory so that adding a second account is more obvious. 

No idea yet what to do with kops vars. Values in `config/local/private/secrets.yml` likely need to be updated and moved to account specific locations in order to support different credentials for different accounts.

**Comment by philipcristiano** [comment]
Having multiple accounts also means separate VPCs. If the multi-account setups are used to split dev and prod, this layout would wind up having separate `vpc` directories.

**Comment by philipcristiano** [comment]
I've updated an infra repo to work with multiple repositories. 

Notable changes:
* `accounts` folder created where `default` would make more sense, and adding multiple accounts is straightforward. 
* TF and Ansible code is moved to top level directories with variable files in each account. This helps when each account/environment should look the same by reducing duplication of configuration.
* Secrets files exist per account but there is still  a `config/private` for keys. These could be moved to appropriate accounts.

More Improvements:
* Having separate environments inside an account makes switching between envs a bit more complex. Operations require the account name and the env name to address an environment. This could be improved by having only separate environments, and account vars linked/included depending on the environment. 
* Kubernetes manifests are still duplicated between accounts/clusters. These could be de-duplicated with Helm or similar templating. 
* Accounts could be flattened a bit more into fewer directories instead of splitting var files for Ansible, shell, and TF. 
* `ansible` and `terraform` folders are not obvious why to have both or what kinds of resources should be created in either. 

```
├── accounts
│   ├── account_1
│   │   ├── account
│   │   │   └── vars.yml
│   │   ├── ansible
│   │   │   └── dev.yml
│   │   ├── clusters
│   │   │   └── dev-1
│   │   │       ├── kubernetes
│   │   │       │   ├── cluster-autoscaler.yml
│   │   │       │   ├── docker-gc.yml
│   │   │       │   ├── heapster-controller.yaml
│   │   │       │   ├── kubernetes-dashboard-v1.6.1.yml
│   │   │       │   ├── namespaces.yml
│   │   │       │   ├── readme.md
│   │   │       │   └── route53-sync.yml
│   │   │       ├── resources
│   │   │       │   └── readme.md
│   │   │       └── vars.sh
│   │   ├── config
│   │   │   ├── local
│   │   │   │   └── vars.yml
│   │   │   └── private
│   │   │       └── secrets.yml
│   │   └── terraform
│   │       └── dev.tfvars
│   └── account_2
│       ├── account
│       │   └── vars.yml
│       ├── ansible
│       │   ├── pre-prod.yml
│       │   └── prod.yml
│       ├── clusters
│       │   ├── pre-prod-1
│       │   │   ├── kubernetes
│       │   │   │   ├── namespaces.yml
│       │   │   │   ├── readme.md
│       │   │   └── vars.sh
│       │   └── prod-1
│       │       ├── kubernetes
│       │       │   ├── namespaces.yml
│       │       │   ├── readme.md
│       │       └── vars.sh
│       ├── config
│       │   ├── local
│       │   │   └── vars.yml
│       │   └── private
│       │       └── secrets.yml
│       └── terraform
│           ├── pre-prod.tfvars
│           └── prod.tfvars
├── ansible
│   ├── Makefile
│   └── vpn.yml
├── ansible-requirements.yml
├── config
│   ├── local
│   │   ├── ansible.cfg
│   │   ├── ansible.cfg-default
│   │   ├── env-vars.sh
│   │   ├── local-config-init
│   │   ├── ssh_config
│   │   ├── ssh_config-default
│   │   ├── vars -> ../private/vars
│   │   └── vars.yml
│   └── private
│       ├── admin-vpn
│       ├── admin-vpn.pub
│       ├── ansible.cfg
│       ├── kube_config
│       ├── prod-vpn
│       ├── prod-vpn.pem
│       ├── prod-vpn.pub
│       ├── secrets.yml
│       ├── ssh_config
│       ├── working-private
│       └── working-private.pub
├── docs
│   └── readme.md
├── kops
│   └── kops.sh
├── plugins
│   ├── filter_plugins
│   │   ├── flatten.py
│   │   └── flatten.pyc
│   └── inventory
│       ├── base
│       ├── ec2.ini
│       └── ec2.py
├── requirements.txt
├── roles
└── terraform
    ├── Makefile
    ├── main.tf
    └── variables.tf
```

**Comment by ejether** [comment]
closed by https://github.com/reactiveops/pentagon/pull/99
