### ISSUE TITLE
Setup steps mention otherwise undocument tools 

### ISSUE THREAD

**Issue by philipcristiano** [FairwindsOps/pentagon#57]
After `start-project` the `workon` command is mentioned, but not documented how to get it https://github.com/reactiveops/pentagon/blob/15f4dfd7da9bfd3af4a3c21832e34e657a1c7d3e/bin/pentagon#L96 https://github.com/reactiveops/pentagon/blob/15f4dfd7da9bfd3af4a3c21832e34e657a1c7d3e/docs/getting-started.md

The instructions should be agnostic of our internal workstation setup.

**Comment by ejether** [comment]
fixed in #66
