### ISSUE TITLE
vpn_bucket defined twice

### ISSUE THREAD

**Issue by philipcristiano** [FairwindsOps/pentagon#58]
The `vpn_bucket` appears defined twice:
* [By account](https://github.com/reactiveops/pentagon/blob/15f4dfd7da9bfd3af4a3c21832e34e657a1c7d3e/lib/pentagon/default/account/vars.yml.jinja#L7)
* [By environment](https://github.com/reactiveops/pentagon/blob/15f4dfd7da9bfd3af4a3c21832e34e657a1c7d3e/lib/pentagon/default/resources/admin-environment/env.yml.jinja#L18)

Both files are sourced in the [VPN play](https://github.com/reactiveops/pentagon/blob/15f4dfd7da9bfd3af4a3c21832e34e657a1c7d3e/lib/pentagon/default/resources/admin-environment/vpn.yml#L10)

This seems duplicative at best and at worst a source of bugs/frustration. If the buckets are needed to be defined twice we should include comments about why each should be set a certain way.

**Comment by ejether** [comment]
fixed
