### ISSUE TITLE
Replacing VPN instance recreates VPN keys

### ISSUE THREAD

**Issue by philipcristiano** [FairwindsOps/pentagon#63]
Replacing the VPN instance in a VPC winds up replacing the client VPN keys. If the keys exist already I believe the existing keys should be used unless explicitly recreating them. Replacing the VPN instance does not seem like a case to recreate them. When the keys are overwritten this can cause a burden to redistribute keys to existing OpenVPN users.

The VPN role will [use existing keys when told that this is not a first run](https://github.com/reactiveops/Stouts.openvpn/blob/678ed03af8194a2a0133a25a08eb7d1d2981ae48/tasks/configure.yml#L28).

[We set `openvpn_first_run`](https://github.com/reactiveops/pentagon/blob/8df454ef8357c55b7d127defd5b8bf005d2758a3/lib/pentagon/default/resources/admin-environment/vpn.yml#L32) based on [creating the instance](https://github.com/reactiveops/ansible-vpn-stack/blob/062a090c6eb1337c87aa98a0b34e8c2c1c65e0df/tasks/create-instance.yml#L26). The `first_run` should try to detect if existing keys/config exists and set `openvpn_first_run` appropriately.

**Comment by opennomad** [comment]
I believe it will be more complex to accomplish this. The `openvpn_first_run` value is used several times in https://github.com/reactiveops/Stouts.openvpn/blob/master/tasks/configure.yml. Without it the server won't end up being configured for service. Perhaps this is an augmentation that better fits in the VPN role?

**Comment by philipcristiano** [comment]
In  reviewing the above linked code it looks like things would progress when it is not `no`, as the creation happens regardless of the setting. The setting seems to trigger copying back down from S3. 

When creating VPN instances I rely on the SSH config file for SSH, which fails after the instance is created, until the IP/config is added to the SSH config. A [setting](https://github.com/reactiveops/pentagon/blob/f3b31bdfed83f4ed55d1d3d7a74b285bf2eb76d3/lib/pentagon/default/resources/admin-environment/vpn.yml#L50) is passed through from the [VPN stack](https://github.com/reactiveops/ansible-vpn-stack/blob/master/tasks/create-instance.yml#L27) which looks like it would be `no` on the first SSH'd run to the instance.
